#!/usr/bin/env python3
"""
scaffold_build_pack.py — lay out an implementation-KP build pack skeleton.

Creates the fixed build-pack anatomy (configs / prompts / scripts / acceptance /
runbook / manifest) for one KP track, with a populated manifest.yaml and one
prompt + acceptance stub per module. Pure standard library; runs offline.

Usage:
  python3 scaffold_build_pack.py <KP> <track> [options]

  <KP>     KP2 | KP3 | KP4   (the topic number is taken from the digit)
  <track>  interoperability | dpi | service-delivery

Options:
  --out DIR        output directory (default: ./<KP>-build-pack)
  --bbs a,b,c      override the Building-Block set
  --modules N      number of modules (default 6)
  --force          overwrite an existing pack directory

The manifest is the spine kp-solution-verify reads: per module it records the
Building Block(s), the config artefact, the generating prompt and the acceptance
check. Fill the configs with bb-config-gen; prove the pack with kp-solution-verify.
"""
import argparse
import os
import sys

TRACKS = {
    "interoperability": {
        "title": "Government Interoperability Framework",
        "depends_on": [],
        "ext": "conf",
        "bbs": ["x-road-bus", "member-plr", "member-pnea", "member-pnia"],
    },
    "dpi": {
        "title": "Education Digital Public Infrastructure",
        "depends_on": ["KP2"],
        "ext": "yaml",
        "bbs": ["registry-mds", "identity", "payment-paypro", "consent", "notification"],
    },
    "service-delivery": {
        "title": "Digital Government Services (Building Block Approach)",
        "depends_on": ["KP2", "KP3"],
        "ext": "yaml",
        "bbs": ["svc-learner-registration", "svc-scholarship", "svc-credential"],
    },
}

PROMPT_STUB = """# Generating prompt — module {mod}

**Building block(s):** {bbs}
**Produces:** `{config}`
**Public spec:** [confirm — cite the GovStack BB spec / X-Road API / EIF layer / W3C VC]

## Problem
[What configuration this prompt produces and why a learner needs it.]

## Prompt (copy-paste ready)
```
[The prompt whose OUTPUT is the configuration artefact above.
 Open with "Below is ..." naming the spec + service brief pasted in.
 Decompose into the named config fields. End with the exact output format.]
```

## Inputs / outputs
- **Inputs:** [the BB spec section + the Progressa service brief]
- **Output:** [the config artefact written to configs/]

## Safeguard
[The specific failure mode to guard — e.g. "validate every identifier against the
registered subsystem list before deploy; a wrong member ID silently breaks routing".]
"""

ACCEPTANCE_STUB = """# Acceptance check — module {mod}

**Proves:** [the slice this module builds actually runs]
**Run by:** `scripts/acceptance.*` (reuse joget-db-inspect / X-Road test call)

- **Given** [the pack is deployed and seeded on the Linkup/Joget stack]
- **When** [the action — e.g. a once-only query from PNEA to PLR over X-Road]
- **Then** [the observable result — e.g. the learner record returns once, no re-entry;
  joget-db-inspect shows the expected state/count]

Status: UNVERIFIED until this passes on the live stack (kp-solution-verify).
"""

RUNBOOK_STUB = """# {kp} build pack — run book

Stand this slice up from zero on the Linkup (X-Road) + Joget stack.

## Prerequisites
{prereqs}
- ITU cloud access live (Linkup + Joget DX 8.x) — Inception Report action item A4.

## Steps
1. Deploy the configs:  `scripts/deploy.*`
2. Seed Progressa demo data:  `scripts/seed.*`
3. Run the acceptance suite:  `scripts/acceptance.*`

## Teardown
[How to reset the slice.]

> Reproducible: every step is a script in `scripts/`, every config is generated by
> bb-config-gen. Do not hand-edit a config in `configs/` — regenerate it.
"""

README_STUB = """# {kp} build pack — {track_title}

The runnable companion to the {kp} video bundle. The videos teach the build; this
pack **is** the ready solution — the configuration the modules generate, the prompts
that generate it, the scripts that deploy it, and the acceptance checks that prove it.

- **Track:** {track}
- **Depends on:** {depends}
- **Stand it up:** see `runbook.md`
- **Index:** see `manifest.yaml` (module → BB → config → prompt → acceptance)

Built and proven with the `itu-giga-kp` kit: `bb-config-gen` fills the configs,
`kp-solution-verify` proves the pack runs. Scope: Education only, public anchors only.
"""

DEPLOY_STUB = """#!/usr/bin/env bash
# Deploy {kp} configs onto the live stack. Reuse joget-deploy (KP4) / X-Road CLI (KP2)
# / the mtca-data-platform MDM load (KP3). Runs on the workstation against ITU cloud,
# NOT in the sandbox (see mtca-dev-workflow two-track method).
set -euo pipefail
echo "TODO: deploy configs/ for {kp}"
"""

ACCEPT_SCRIPT_STUB = """#!/usr/bin/env bash
# Run the {kp} acceptance suite (one check per module in acceptance/).
# Reuse joget-db-inspect queries / X-Road test calls. Exit non-zero on first failure.
set -euo pipefail
echo "TODO: run acceptance/ checks for {kp}"
"""

SEED_STUB = """#!/usr/bin/env bash
# Seed Progressa demo data for {kp}. Keep institution names + BB ids identical across
# packs (they are the join keys for the cumulative Progressa solution).
set -euo pipefail
echo "TODO: seed Progressa demo data for {kp}"
"""


def y_list(items):
    return "[" + ", ".join(items) + "]" if items else "[]"


def build_manifest(kp, track, info, bbs, modules):
    lines = []
    lines.append(f"kp: {kp}")
    lines.append(f"track: {track}")
    lines.append(f"title: {info['title']}")
    lines.append(f"home: 10-Knowledge-Products/{kp}-{track[:3].upper()}")
    lines.append(f"depends_on: {y_list(info['depends_on'])}")
    lines.append("building_blocks:")
    for b in bbs:
        lines.append(f"  - {b}")
    ext = info.get("ext", "yaml")
    lines.append("modules:")
    for m in modules:
        primary_bb = bbs[(int(m.split('.')[1]) - 1) % len(bbs)]
        lines.append(f"  - id: \"{m}\"")
        lines.append(f"    title: \"\"")
        lines.append(f"    building_blocks: {y_list([primary_bb])}")
        lines.append(f"    config: configs/{primary_bb}/{m}.{ext}")
        lines.append(f"    prompt: prompts/{m}.md")
        lines.append(f"    acceptance: acceptance/{m}.md")
    return "\n".join(lines) + "\n"


def write(path, content, force):
    if os.path.exists(path) and not force:
        print(f"  skip (exists): {path}")
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  wrote: {path}")


def main():
    ap = argparse.ArgumentParser(description="Scaffold an implementation-KP build pack.")
    ap.add_argument("kp")
    ap.add_argument("track", choices=sorted(TRACKS.keys()))
    ap.add_argument("--out")
    ap.add_argument("--bbs")
    ap.add_argument("--modules", type=int, default=6)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    kp = args.kp.upper()
    digit = "".join(c for c in kp if c.isdigit())
    if not digit:
        sys.exit(f"error: could not read a topic number from '{kp}' (expected KP2/KP3/KP4)")
    info = TRACKS[args.track]
    bbs = [b.strip() for b in args.bbs.split(",")] if args.bbs else list(info["bbs"])
    modules = [f"{digit}.{i}" for i in range(1, args.modules + 1)]
    out = args.out or f"./{kp}-build-pack"

    if os.path.isdir(out) and os.listdir(out) and not args.force:
        sys.exit(f"error: {out} exists and is not empty (use --force)")

    print(f"Scaffolding {kp} build pack ({args.track}) at {out}")
    write(os.path.join(out, "manifest.yaml"),
          build_manifest(kp, args.track, info, bbs, modules), True)
    write(os.path.join(out, "README.md"),
          README_STUB.format(kp=kp, track=args.track, track_title=info["title"],
                             depends=", ".join(info["depends_on"]) or "none (foundation)"),
          True)
    prereqs = "\n".join(f"- {d} build pack deployed (it is the layer below)."
                        for d in info["depends_on"]) or "- none — this is the foundation track."
    write(os.path.join(out, "runbook.md"),
          RUNBOOK_STUB.format(kp=kp, prereqs=prereqs), True)

    for b in bbs:
        keep = os.path.join(out, "configs", b, ".gitkeep")
        write(keep, "", True)
    for m in modules:
        primary_bb = bbs[(int(m.split('.')[1]) - 1) % len(bbs)]
        write(os.path.join(out, "prompts", f"{m}.md"),
              PROMPT_STUB.format(mod=m, bbs=primary_bb,
                                 config=f"configs/{primary_bb}/{m}.placeholder"), True)
        write(os.path.join(out, "acceptance", f"{m}.md"),
              ACCEPTANCE_STUB.format(mod=m), True)

    for name, stub in (("deploy.sh", DEPLOY_STUB), ("seed.sh", SEED_STUB),
                       ("acceptance.sh", ACCEPT_SCRIPT_STUB)):
        write(os.path.join(out, "scripts", name), stub.format(kp=kp), True)

    print(f"\nDone. {len(modules)} modules, {len(bbs)} building blocks.")
    print("Next: fill configs with bb-config-gen, then prove with kp-solution-verify.")


if __name__ == "__main__":
    main()
