"""Play 0 — Build your country context. The context prompts are the ones used in the Gambia test
runs (Aug 2026), cleaned into the four-part shape and de-personalised (posts, not names)."""

SECTIONS = [
dict(n=1, title="Digital-landscape brief", feeds="1.1, 1.2", skill="country-context-pack",
     prompt="""I am preparing to assess [country X]'s readiness for a national Enterprise Architecture. Using public sources only, write 3–4 paragraphs of context on [country X]'s digital landscape, under these headings: (1) connectivity and affordability; (2) the digital-government strategy in force and the body that owns it; (3) the identity programme and any cross-agency systems — data exchange, payments, civil registration; (4) maturity and key gaps, citing any published index or readiness assessment. Name institutions, systems and documents, with the year of each. Cite a public source URL for every substantive claim and state the data year. Do not name individual office-holders. Return the brief as text in this chat.""",
     output="A dated, sourced brief of 3–4 paragraphs. It is the input to 1.1 and supplies the named institutions and services for 1.2."),
dict(n=2, title="Programme list", feeds="1.3, 1.5", skill="country-context-pack",
     prompt="""List 3–5 current or planned digital-government programmes in [country X]'s [sector] sector. For each give: name; status (planned / procurement / live / scaling); year started or approved; funder(s) and budget envelope if public; the lead body; and which of identity, payments, data exchange, registration and consent components the programme needs. Add 2–3 cross-cutting observations (connectivity, financing, sequencing). Cite a public source URL for each programme. Return the list as text in this chat.""",
     output="A programme list with budgets and building-block needs — the input to the business case (1.3) and the foundation map (1.5)."),
dict(n=3, title="Ministry operating context", feeds="1.4", skill="country-context-pack",
     prompt="""Describe how [country X]'s [ministry] works, from public sources, under these headings: institutional structure (including any split between ministries and the degree of decentralisation); policy framework and sector plan in force; legal constraints; financial constraints, including donor dependence and any documented public-financial-management failures; technical and data-system constraints; human-resource constraints; and political context (reporting obligations, delivery forums). End with a one-paragraph note on what is absent from the public record. Cite a source URL per claim. Refer to posts, not named individuals. Return as text in this chat.""",
     output="The context paragraphs the operating-model question in 1.4 is decomposed against."),
dict(n=4, title="Institutional roles register", feeds="1.6, 1.7", skill="country-context-pack",
     prompt="""Build a register of the institutional roles relevant to a national Enterprise Architecture programme in [country X], by post — not by the name of the current holder. Cover: the CDO/CTO or political equivalent; the head of the civil service; the national ICT or e-government agency and its board; sector ministry CIOs or ICT unit heads; any existing EA function or chief architect; any governance board with cross-government authority; the procurement authority; the data-protection regulator; the budget authority; the government CISO; the interoperability-standards function. For each role give: the institution, a one-line mandate, and a status tag — confirmed (exists, holder in post), partial (exists but unclear or unstaffed) or gap (does not exist). End with a list of roles an EA programme needs that are missing. Base everything on public material; where something cannot be found, say so and move on. Return as text in this chat.""",
     output="A roles register with a status tag per role. It is the input to the RACI (1.6); the gap list re-appears as the membership section of the Board terms of reference (1.7)."),
dict(n=5, title="Country characteristics", feeds="Module 5 (5.1)", skill="country-context-pack",
     prompt="""Write a one-paragraph characteristics line for [country X] to be used when searching for comparable countries: population; income classification; governance type (unitary / federal / hybrid) and degree of sub-national autonomy; region and regional bodies; digital-government maturity (published index rankings, readiness assessments); state of national ID, civil registration, data exchange and payments infrastructure; the coordinating digital body and whether its mandate is binding; budget-cycle constraints; main donors funding sectoral systems; and whether an EA function or governance board exists. Cite sources. Return as text in this chat.""",
     output="The characteristics line pasted into the comparator play (5.1, Module 5)."),
dict(n=6, title="Public bodies, systems and registries", feeds="Module 2 (2.1, 2.4, 2.5), Module 4 (4.1)", skill="bdat-assessor, ea-method-runner",
     prompt="""For [country X]'s [sector] sector, list the public bodies that matter — the ministry or ministries, examinations or regulatory bodies, registries, and the shared-platform providers (identity, civil registration, payments, data exchange). For each give: name; mandate; known systems it runs; known registries it holds; and a confidence note (confirmed / inferred). Base it on public material; where a body you would expect does not appear to exist, say so. Return as a table plus notes, as text in this chat.""",
     output="The sector body table that Module 2's four-layer reading and Module 4's demonstration canvas start from."),
dict(n=7, title="Legal and policy list", feeds="Module 2 (2.3)", skill="country-context-pack",
     prompt="""From public material, list the laws and policy instruments that constrain digital-government and [sector] programmes in [country X]: the data-protection act (status, regulator, key obligations for minors' data if relevant), the procurement law and any e-procurement rules, any e-government or digital-transactions act or decree, the access-to-information act, the sector act, and the strategies in force. For each: title, year, status (enacted / bill / draft), owning body, and the one constraint it places on a data-sharing or shared-platform design. Cite sources. Return as text in this chat.""",
     output="The legal context used in Module 2's principles work (2.3) and in every consent or legal-basis decision downstream."),
]
