#!/usr/bin/env python3
"""
new_bb_config.py — scaffold one Building-Block config artefact + its generating prompt.

Writes a config stub (with [confirm] placeholders, never invented values) into
configs/<bb>/ and a four-part generating-prompt stub into prompts/<module>.md,
pre-filled with the right PUBLIC spec pointer for the block. Pure standard library.

The actual config is then generated for real by the routed engine (X-Road / mtca /
joget-*) against the public spec + the Progressa service brief; this just lays out a
consistent, citeable starting point. See references/bb-spec-map.md.

Usage:
  python3 new_bb_config.py <track> <bb> --module <m.n> [--out <pack_dir>]

  <track>  interoperability | dpi | service-delivery
  <bb>     e.g. member-plr, registry-mds, svc-scholarship  (see bb-spec-map.md)
"""
import argparse
import os
import sys

# (spec to CITE, internal engine to route to, artefact kind/extension)
SPECMAP = {
    "interoperability": {
        "_default": ("NIIS X-Road docs (niis.org); EIF Technical layer",
                     "X-Road CLI / admin REST API", "conf"),
        "x-road-bus": ("NIIS X-Road docs (niis.org); EIF Technical layer",
                       "X-Road central/security server config", "conf"),
        "member-plr": ("X-Road member/subsystem registration + service-description API",
                       "X-Road CLI", "conf"),
        "member-pnea": ("X-Road subsystem + access-control (ACL) API", "X-Road CLI", "conf"),
        "member-pnia": ("X-Road subsystem + OpenAPI/WSDL service description",
                        "X-Road CLI", "conf"),
    },
    "dpi": {
        "_default": ("GovStack BB spec (govstack.global); UNDP DPI Maturity",
                     "mtca-data-platform / adapter", "yaml"),
        "registry-mds": ("GovStack Registration/Registries BB; UNDP DPI Maturity",
                         "mtca-data-platform: build-dbt-model / add-dq-checks", "yaml"),
        "identity": ("GovStack Identity BB; World Bank ID4D",
                     "mtca-data-platform: expose-api + adapter", "yaml"),
        "payment-paypro": ("GovStack Payment BB", "payment adapter", "yaml"),
        "consent": ("GovStack Consent BB", "consent policy adapter", "yaml"),
        "notification": ("GovStack Notification / Information Mediation BB",
                         "notification adapter", "yaml"),
    },
    "service-delivery": {
        "_default": ("GovStack BB patterns (PAERA Annex A1.3); Joget DX 8.x docs",
                     "joget-* loop (req-analyst → component-architect → form/workflow gen)", "yaml"),
        "svc-learner-registration": ("GovStack BB patterns; Joget DX 8.x docs",
                                      "joget-* loop", "yaml"),
        "svc-scholarship": ("GovStack Payment BB; Joget DX 8.x docs", "joget-* loop", "yaml"),
        "svc-credential": ("W3C Verifiable Credentials Data Model; Joget DX 8.x docs",
                           "joget-* loop + VC issuance", "yaml"),
    },
}

CONFIG_STUB = """# {bb} — configuration artefact (module {module})
# Track: {track}
# CITE (public spec): {spec}
# Engine (internal, do NOT cite): {engine}
#
# Generated by bb-config-gen against the public spec + the Progressa service brief.
# Every value below is [confirm: ...] until checked against the spec or the live
# registry. Do not invent identifiers — a wrong id silently breaks routing.

building_block: {bb}
module: "{module}"
# --- fill from the spec, confirm each value ---
identifier: "[confirm: the registered id from the spec / live registry]"
endpoints: "[confirm: from the public spec]"
access_control: "[confirm: who may call this, per the data-sharing agreement]"
# ... add the fields the spec defines ...
"""

PROMPT_STUB = """# Generating prompt — module {module} ({bb})

**Building block:** `{bb}`
**Produces:** `configs/{bb}/{module}.{ext}`
**Public spec (cite this):** {spec}
**Engine (internal routing, not a citation):** {engine}

## Problem
[The configuration this prompt produces, and the Progressa exchange/service it enables.]

## Prompt (copy-paste ready)
```
Below is (a) the relevant section of {spec} and (b) the Progressa service brief
for {bb}.

[paste the spec section]
[paste the Progressa service brief]

Produce the configuration for {bb} as <artefact kind>. For each field, use only
values present in the spec or the brief; where a value must come from the live
registry, output [confirm: <what to look up>] rather than a guess.

Output: <the exact artefact structure — keys/sections the spec defines>.
```

## Inputs / outputs
- **Inputs:** the cited spec section + the Progressa service brief
- **Output:** `configs/{bb}/{module}.{ext}` (replaces the stub)

## Safeguard
Validate every identifier against the published spec or the live registry before
deploy. Treat any `[confirm: ...]` as unresolved — it must be closed, not shipped.
"""


def get_spec(track, bb):
    table = SPECMAP[track]
    return table.get(bb, table["_default"])


def write(path, content, force):
    if os.path.exists(path) and not force:
        print(f"  skip (exists, use --force): {path}")
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  wrote: {path}")


def main():
    ap = argparse.ArgumentParser(description="Scaffold a BB config artefact + generating prompt.")
    ap.add_argument("track", choices=sorted(SPECMAP.keys()))
    ap.add_argument("bb")
    ap.add_argument("--module", required=True, help="e.g. 2.4")
    ap.add_argument("--out", default=".", help="the build-pack directory")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    spec, engine, ext = get_spec(args.track, args.bb)
    if args.bb not in SPECMAP[args.track]:
        print(f"  note: '{args.bb}' not in the map — using the track default spec. "
              f"Add it to references/bb-spec-map.md.")

    cfg = os.path.join(args.out, "configs", args.bb, f"{args.module}.{ext}")
    prm = os.path.join(args.out, "prompts", f"{args.module}.md")
    write(cfg, CONFIG_STUB.format(bb=args.bb, module=args.module, track=args.track,
                                  spec=spec, engine=engine), args.force)
    write(prm, PROMPT_STUB.format(bb=args.bb, module=args.module, spec=spec,
                                  engine=engine, ext=ext), args.force)
    print("\nNext: run the routed engine to generate the real config, then define the "
          "acceptance check and verify with kp-citation-verify + kp-solution-verify.")


if __name__ == "__main__":
    main()
