-- Bronze DDL for source 'pemis' — 3 tables
-- Generated by gen_bronze_ddl.py · review before applying · money widened to Decimal(38,s)

-- pemis.censusreturn (52,917 rows)
CREATE TABLE IF NOT EXISTS `bronze`.`pemis__censusreturn`
(
    `crt_serial` Int64,
    `crt_schref` Int32,
    `crt_year` Int16,
    `crt_boys` Nullable(Int32),
    `crt_girls` Nullable(Int32),
    `crt_total` Nullable(Int32),
    `crt_teachers` Nullable(Int32),
    `_extracted_at` DateTime64(3),
    `_batch_id` String,
    `_source` LowCardinality(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(`_extracted_at`)
ORDER BY (`crt_serial`);

-- pemis.district (38 rows)
CREATE TABLE IF NOT EXISTS `bronze`.`pemis__district`
(
    `dis_serial` Int64,
    `dis_name` String,
    `dis_province` Nullable(String),
    `_extracted_at` DateTime64(3),
    `_batch_id` String,
    `_source` LowCardinality(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(`_extracted_at`)
ORDER BY (`dis_serial`);

-- pemis.school (4,812 rows)
CREATE TABLE IF NOT EXISTS `bronze`.`pemis__school`
(
    `sch_serial` Int64,
    `sch_code` String,
    `sch_name` Nullable(String),
    `sch_disref` Nullable(Int32),
    `sch_capacity` Nullable(Int32),
    `sch_grant` Nullable(Decimal(38, 2)),
    `_extracted_at` DateTime64(3),
    `_batch_id` String,
    `_source` LowCardinality(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(`_extracted_at`)
ORDER BY (`sch_serial`);

